{% set name = "ChemDataExtractor-CSR" %}
{% set version = "1.3.0CSR" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/edbeard/chemdataextractor-csr.git
  git_rev: v1.3.0-CSR

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
    - python=3.6
    - dawg
  run:
    - appdirs
    - beautifulsoup4
    - click
    - cssselect
    - dawg
    - lxml
    - nltk
    - pdfminer.six
    - python-crfsuite
    - python-dateutil
    - pyyaml
    - requests
    - six

test:
  imports:
    - chemdataextractor
  commands:
    - cde --help

about:
  home: http://chemschematicresolver.org
  license: MIT
  license_file: LICENSE
  summary: 'Automatically extract chemical information from scientific documents. Designed to be used in tandem with ChemSchematicResolver'
  doc_url: http://chemdataextractor.org/docs
  dev_url: https://github.com/edbeard/ChemDataExtractor-CSR

extra:
  recipe-maintainers:
    - edbeard
